apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-recipe-app-ingress
  annotations:
    kubernetes.io/spec.ingressClassName: "gce"  # Use "gce" for GKE Ingress
    kubernetes.io/ingress.global-static-ip-name: "recipe-app"
    networking.gke.io/managed-certificates: "frontend-recipe-app-cert"  # Link Managed Certificate
spec:
  rules:
    - host: diningservices.vishalgandla.online  # Your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-recipe-app  # Your service name
                port:
                  number: 80  # Adjust to match your service port
